INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (6, 'Søren Heisel', 1);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (7, 'Anne Hjorth', 1);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (8, 'Jesper Kampmann', 1);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (9, 'Ole Lund Petersen', 1);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (10, 'Gitte H. Terndrup', 1);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (11, 'Karl Gaub', 1);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (12, 'Rasmus Kruse', 1);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (13, 'Bjarne Burkal', 1);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (14, 'Malthe Poulsen', 1);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (15, 'Kristine Kryger', 2);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (16, 'Anders Hartzen', 2);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (17, 'Henrik Nielsen', 2);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (18, 'Martin Iversen', 2);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (19, 'Carsten Lassen', 2);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (20, 'Birger Hesse', 2);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (21, 'Anders Jensen', 2);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (22, 'Melitta Naegeli', 2);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (23, 'Katrine Lotz', 2);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (24, 'Karina Probst-Rasmussen', 2);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (25, 'Hans Toft', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (26, 'Pia Nyring', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (27, 'Michael Fenger', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (28, 'Marianne Zangenberg', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (29, 'Ulrik Borch', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (30, 'Karen Riis Kjølbye', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (31, 'Katja S.Johansen', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (32, 'Bente Frimodt-Møller', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (33, 'Jesper Kamp Nielsen', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (34, 'Christian Buje Tingleff', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (35, 'Louisa S.Bøttkjær', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (36, 'Jakob Vilner', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (37, 'Niels Lund', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (38, 'Per Bruun Andersen', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (39, 'Katarina Ammitzbøll', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (40, 'Jesper Marcus', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (41, 'Birgitte Schmidt', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (42, 'Andreas Weidinger', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (43, 'Thomas Rostrup', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (44, 'Jan Sandberg', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (45, 'Susanne Biltoft', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (46, 'Anders Holde', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (47, 'Ole Stephensen', 3);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (48, 'Poul V.Jensen', 4);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (49, 'Henrik Engel Elborough', 4);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (50, 'Erik Friedlænder', 4);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (51, 'Nina Froberg', 4);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (52, 'Arent Christian Kjær', 4);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (53, 'Lars Kiil', 4);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (54, 'Leo Lundø', 4);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (55, 'Charlotte Petersen', 4);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (56, 'Ivan Léon Siehr', 4);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (57, 'Henrik Vendelbo', 4);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (58, 'Brigitta Rick', 5);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (59, 'John Andersen', 5);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (60, 'Dina Wildt', 5);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (61, 'Jens Ahm', 5);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (62, 'Peder Larsen', 5);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (63, 'Cecilia Catharina Buchtrup', 6);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (64, 'Mette Fabricius-Lauritzen', 6);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (65, 'Lasse Evers Andersen', 6);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (66, 'Carmen Torpenhow', 7);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (67, 'Rita Russell', 8);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (68, 'Henrik Thorup', 8);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (69, 'Tina Wittendorf', 8);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (70, 'Jesper Villadsen', 8);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (71, 'Anne Lundquist1', 8);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (72, 'Connie Søegaard', 8);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (73, 'Annet Malmqvist', 8);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (74, 'Louise Feilberg', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (75, 'Morten Løkkegaard', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (76, 'Malene Hartvigsen', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (77, 'Egil Rindorf', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (78, 'Tine Horwitz', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (79, 'Henrik Thormod Andersen', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (80, 'Nils Juhl Andreasen', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (81, 'Jesper Holm', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (82, 'Joan Jørgensen', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (83, 'Jens Tarp', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (84, 'Erik Ross Pedersen', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (85, 'Kirsten Elvstrøm', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (86, 'Kjeld Danneskiold-Samsøe', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (87, 'Morten Munk Ebbesen', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (88, 'Pia Loft', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (89, 'Colette Brix', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (90, 'Anders Munk Ebbesen', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (91, 'Hans-Georg Nielsen', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (92, 'Allan Stoere', 9);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (93, 'Jeanne Toxværd', 10);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (94, 'Frederik Dehlholm', 10);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (95, 'Tage Christiansen', 10);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (96, 'Line Traugott', 10);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (97, 'Magne Edvard Pihl', 10);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (98, 'Regula Maltry', 10);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (99, 'Jens Henrik Wiene', 11);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (100, 'Elizabeth Kristensen', 11);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (101, 'Marianne Victor Hansen', 11);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (102, 'Ove Lund', 11);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (103, 'Gitte Haslebo', 11);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (104, 'Lise Lauritzen Loft', 11);
INSERT INTO kommunalvalg_exam.candidates (id, name, party_id) VALUES (105, 'Helle Laustsen', 11);